<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [1, 'Afghanistan', 'AF', 'AFG', '93', 'AFN', 'Afghani', '؋', 1],
            [2, 'Albania', 'AL', 'ALB', '355', 'ALL', 'Lek', 'L', 1],
            [3, 'Algeria', 'DZ', 'DZA', '213', 'DZD', 'Algerian Dinar', 'د.ج', 1],
            [4, 'American Samoa', 'AS', 'ASM', '1-684', 'USD', 'US Dollar', '$', 1],
            [5, 'Andorra', 'AD', 'AND', '376', 'EUR', 'Euro', '€', 1],
            [6, 'Angola', 'AO', 'AGO', '244', 'AOA', 'Kwanza', 'Kz', 1],
            [7, 'Anguilla', 'AI', 'AIA', '1-264', 'XCD', 'East Caribbean Dollar', '$', 1],
            [8, 'Antarctica', 'AQ', 'ATA', '672', NULL, NULL, NULL, 1],
            [9, 'Antigua and Barbuda', 'AG', 'ATG', '1-268', 'XCD', 'East Caribbean Dollar', '$', 1],
            [10, 'Argentina', 'AR', 'ARG', '54', 'ARS', 'Argentine Peso', '$', 1],
            [11, 'Armenia', 'AM', 'ARM', '374', 'AMD', 'Armenian Dram', '֏', 1],
            [12, 'Aruba', 'AW', 'ABW', '297', 'AWG', 'Aruban Florin', 'ƒ', 1],
            [13, 'Australia', 'AU', 'AUS', '61', 'AUD', 'Australian Dollar', '$', 1],
            [14, 'Austria', 'AT', 'AUT', '43', 'EUR', 'Euro', '€', 1],
            [15, 'Azerbaijan', 'AZ', 'AZE', '994', 'AZN', 'Azerbaijanian Manat', '₼', 1],
            [16, 'Bahamas', 'BS', 'BHS', '1-242', 'BSD', 'Bahamian Dollar', '$', 1],
            [17, 'Bahrain', 'BH', 'BHR', '973', 'BHD', 'Bahraini Dinar', '.د.ب', 1],
            [18, 'Bangladesh', 'BD', 'BGD', '880', 'BDT', 'Taka', '৳', 1],
            [19, 'Barbados', 'BB', 'BRB', '1-246', 'BBD', 'Barbados Dollar', '$', 1],
            [20, 'Belarus', 'BY', 'BLR', '375', 'BYN', 'Belarusian Ruble', 'Br', 1],
            [21, 'Belgium', 'BE', 'BEL', '32', 'EUR', 'Euro', '€', 1],
            [22, 'Belize', 'BZ', 'BLZ', '501', 'BZD', 'Belize Dollar', '$', 1],
            [23, 'Benin', 'BJ', 'BEN', '229', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [24, 'Bermuda', 'BM', 'BMU', '1-441', 'BMD', 'Bermudian Dollar', '$', 1],
            [25, 'Bhutan', 'BT', 'BTN', '975', 'BTN', 'Ngultrum', 'Nu.', 1],
            [26, 'Bolivia, Plurinational State of', 'BO', 'BOL', '591', 'BOB', 'Boliviano', 'Bs.', 1],
            [27, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '599', 'USD', 'US Dollar', '$', 1],
            [28, 'Bosnia and Herzegovina', 'BA', 'BIH', '387', 'BAM', 'Convertible Mark', 'KM', 1],
            [29, 'Botswana', 'BW', 'BWA', '267', 'BWP', 'Pula', 'P', 1],
            [30, 'Bouvet Island', 'BV', 'BVT', '47', 'NOK', 'Norwegian Krone', 'kr', 1],
            [31, 'Brazil', 'BR', 'BRA', '55', 'BRL', 'Brazilian Real', 'R$', 1],
            [32, 'British Indian Ocean Territory', 'IO', 'IOT', '246', 'USD', 'US Dollar', '$', 1],
            [33, 'Brunei Darussalam', 'BN', 'BRN', '673', 'BND', 'Brunei Dollar', '$', 1],
            [34, 'Bulgaria', 'BG', 'BGR', '359', 'BGN', 'Bulgarian Lev', 'лв', 1],
            [35, 'Burkina Faso', 'BF', 'BFA', '226', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [36, 'Burundi', 'BI', 'BDI', '257', 'BIF', 'Burundi Franc', 'FBu', 1],
            [37, 'Cambodia', 'KH', 'KHM', '855', 'KHR', 'Riel', '៛', 1],
            [38, 'Cameroon', 'CM', 'CMR', '237', 'XAF', 'CFA Franc BEAC', 'FCFA', 1],
            [39, 'Canada', 'CA', 'CAN', '1', 'CAD', 'Canadian Dollar', '$', 1],
            [40, 'Cape Verde', 'CV', 'CPV', '238', 'CVE', 'Cabo Verde Escudo', '$', 1],
            [41, 'Cayman Islands', 'KY', 'CYM', '1-345', 'KYD', 'Cayman Islands Dollar', '$', 1],
            [42, 'Central African Republic', 'CF', 'CAF', '236', 'XAF', 'CFA Franc BEAC', 'FCFA', 1],
            [43, 'Chad', 'TD', 'TCD', '235', 'XAF', 'CFA Franc BEAC', 'FCFA', 1],
            [44, 'Chile', 'CL', 'CHL', '56', 'CLP', 'Chilean Peso', '$', 1],
            [45, 'China', 'CN', 'CHN', '86', 'CNY', 'Yuan Renminbi', '¥', 1],
            [46, 'Christmas Island', 'CX', 'CXR', '61', 'AUD', 'Australian Dollar', '$', 1],
            [47, 'Cocos (Keeling) Islands', 'CC', 'CCK', '61', 'AUD', 'Australian Dollar', '$', 1],
            [48, 'Colombia', 'CO', 'COL', '57', 'COP', 'Colombian Peso', '$', 1],
            [49, 'Comoros', 'KM', 'COM', '269', 'KMF', 'Comoro Franc', 'CF', 1],
            [50, 'Congo', 'CG', 'COG', '242', 'XAF', 'CFA Franc BEAC', 'FCFA', 1],
            [51, 'Congo, the Democratic Republic of the', 'CD', 'COD', '243', 'CDF', 'Congolese Franc', 'FC', 1],
            [52, 'Cook Islands', 'CK', 'COK', '682', 'NZD', 'New Zealand Dollar', '$', 1],
            [53, 'Costa Rica', 'CR', 'CRI', '506', 'CRC', 'Costa Rican Colon', '₡', 1],
            [54, 'Croatia', 'HR', 'HRV', '385', 'HRK', 'Croatian Kuna', 'kn', 1],
            [55, 'Cuba', 'CU', 'CUB', '53', 'CUP', 'Cuban Peso', '$', 1],
            [56, 'Curaçao', 'CW', 'CUW', '599', 'ANG', 'Netherlands Antillean Guilder', 'ƒ', 1],
            [57, 'Cyprus', 'CY', 'CYP', '357', 'EUR', 'Euro', '€', 1],
            [58, 'Czech Republic', 'CZ', 'CZE', '420', 'CZK', 'Czech Koruna', 'Kč', 1],
            [59, 'Côte d\'Ivoire', 'CI', 'CIV', '225', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [60, 'Denmark', 'DK', 'DNK', '45', 'DKK', 'Danish Krone', 'kr', 1],
            [61, 'Djibouti', 'DJ', 'DJI', '253', 'DJF', 'Djibouti Franc', 'Fdj', 1],
            [62, 'Dominica', 'DM', 'DMA', '1-767', 'XCD', 'East Caribbean Dollar', '$', 1],
            [63, 'Dominican Republic', 'DO', 'DOM', '1-809', 'DOP', 'Dominican Peso', '$', 1],
            [64, 'Ecuador', 'EC', 'ECU', '593', 'USD', 'US Dollar', '$', 1],
            [65, 'Egypt', 'EG', 'EGY', '20', 'EGP', 'Egyptian Pound', '£', 1],
            [66, 'El Salvador', 'SV', 'SLV', '503', 'USD', 'US Dollar', '$', 1],
            [67, 'Equatorial Guinea', 'GQ', 'GNQ', '240', 'XAF', 'CFA Franc BEAC', 'FCFA', 1],
            [68, 'Eritrea', 'ER', 'ERI', '291', 'ERN', 'Nakfa', 'Nfk', 1],
            [69, 'Estonia', 'EE', 'EST', '372', 'EUR', 'Euro', '€', 1],
            [70, 'Ethiopia', 'ET', 'ETH', '251', 'ETB', 'Ethiopian Birr', 'Br', 1],
            [71, 'Falkland Islands (Malvinas)', 'FK', 'FLK', '500', 'FKP', 'Falkland Islands Pound', '£', 1],
            [72, 'Faroe Islands', 'FO', 'FRO', '298', 'DKK', 'Danish Krone', 'kr', 1],
            [73, 'Fiji', 'FJ', 'FJI', '679', 'FJD', 'Fiji Dollar', '$', 1],
            [74, 'Finland', 'FI', 'FIN', '358', 'EUR', 'Euro', '€', 1],
            [75, 'France', 'FR', 'FRA', '33', 'EUR', 'Euro', '€', 1],
            [76, 'French Guiana', 'GF', 'GUF', '594', 'EUR', 'Euro', '€', 1],
            [77, 'French Polynesia', 'PF', 'PYF', '689', 'XPF', 'CFP Franc', '₣', 1],
            [78, 'French Southern Territories', 'TF', 'ATF', '262', 'EUR', 'Euro', '€', 1],
            [79, 'Gabon', 'GA', 'GAB', '241', 'XAF', 'CFA Franc BEAC', 'FCFA', 1],
            [80, 'Gambia', 'GM', 'GMB', '220', 'GMD', 'Dalasi', 'D', 1],
            [81, 'Georgia', 'GE', 'GEO', '995', 'GEL', 'Lari', '₾', 1],
            [82, 'Germany', 'DE', 'DEU', '49', 'EUR', 'Euro', '€', 1],
            [83, 'Ghana', 'GH', 'GHA', '233', 'GHS', 'Ghana Cedi', '₵', 1],
            [84, 'Gibraltar', 'GI', 'GIB', '350', 'GIP', 'Gibraltar Pound', '£', 1],
            [85, 'Greece', 'GR', 'GRC', '30', 'EUR', 'Euro', '€', 1],
            [86, 'Greenland', 'GL', 'GRL', '299', 'DKK', 'Danish Krone', 'kr', 1],
            [87, 'Grenada', 'GD', 'GRD', '1-473', 'XCD', 'East Caribbean Dollar', '$', 1],
            [88, 'Guadeloupe', 'GP', 'GLP', '590', 'EUR', 'Euro', '€', 1],
            [89, 'Guam', 'GU', 'GUM', '1-671', 'USD', 'US Dollar', '$', 1],
            [90, 'Guatemala', 'GT', 'GTM', '502', 'GTQ', 'Quetzal', 'Q', 1],
            [91, 'Guernsey', 'GG', 'GGY', '44', 'GBP', 'Pound Sterling', '£', 1],
            [92, 'Guinea', 'GN', 'GIN', '224', 'GNF', 'Guinea Franc', 'FG', 1],
            [93, 'Guinea-Bissau', 'GW', 'GNB', '245', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [94, 'Guyana', 'GY', 'GUY', '592', 'GYD', 'Guyana Dollar', '$', 1],
            [95, 'Haiti', 'HT', 'HTI', '509', 'HTG', 'Gourde', 'G', 1],
            [96, 'Heard Island and McDonald Islands', 'HM', 'HMD', '672', 'AUD', 'Australian Dollar', '$', 1],
            [97, 'Holy See (Vatican City State)', 'VA', 'VAT', '39-06', 'EUR', 'Euro', '€', 1],
            [98, 'Honduras', 'HN', 'HND', '504', 'HNL', 'Lempira', 'L', 1],
            [99, 'Hong Kong', 'HK', 'HKG', '852', 'HKD', 'Hong Kong Dollar', '$', 1],
            [100, 'Hungary', 'HU', 'HUN', '36', 'HUF', 'Forint', 'Ft', 1],
            [101, 'Iceland', 'IS', 'ISL', '354', 'ISK', 'Iceland Krona', 'kr', 1],
            [102, 'India', 'IN', 'IND', '91', 'INR', 'Indian Rupee', '₹', 1],
            [103, 'Indonesia', 'ID', 'IDN', '62', 'IDR', 'Rupiah', 'Rp', 1],
            [104, 'Iran, Islamic Republic of', 'IR', 'IRN', '98', 'IRR', 'Iranian Rial', '﷼', 1],
            [105, 'Iraq', 'IQ', 'IRQ', '964', 'IQD', 'Iraqi Dinar', 'ع.د', 1],
            [106, 'Ireland', 'IE', 'IRL', '353', 'EUR', 'Euro', '€', 1],
            [107, 'Isle of Man', 'IM', 'IMN', '44', 'GBP', 'Pound Sterling', '£', 1],
            [108, 'Israel', 'IL', 'ISR', '972', 'ILS', 'New Israeli Sheqel', '₪', 1],
            [109, 'Italy', 'IT', 'ITA', '39', 'EUR', 'Euro', '€', 1],
            [110, 'Jamaica', 'JM', 'JAM', '1-876', 'JMD', 'Jamaican Dollar', '$', 1],
            [111, 'Japan', 'JP', 'JPN', '81', 'JPY', 'Yen', '¥', 1],
            [112, 'Jersey', 'JE', 'JEY', '44', 'GBP', 'Pound Sterling', '£', 1],
            [113, 'Jordan', 'JO', 'JOR', '962', 'JOD', 'Jordanian Dinar', 'د.ا', 1],
            [114, 'Kazakhstan', 'KZ', 'KAZ', '7', 'KZT', 'Tense', '₸', 1],
            [115, 'Kenya', 'KE', 'KEN', '254', 'KES', 'Kenyan Shilling', 'KSh', 1],
            [116, 'Kiribati', 'KI', 'KIR', '686', 'AUD', 'Australian Dollar', '$', 1],
            [117, 'Korea, Democratic People\'s Republic of', 'KP', 'PRK', '850', 'KPW', 'North Korean Won', '₩', 1],
            [118, 'Korea, Republic of', 'KR', 'KOR', '82', 'KRW', 'Won', '₩', 1],
            [119, 'Kuwait', 'KW', 'KWT', '965', 'KWD', 'Kuwaiti Dinar', 'د.ك', 1],
            [120, 'Kyrgyzstan', 'KG', 'KGZ', '996', 'KGS', 'Som', 'с', 1],
            [121, 'Lao People\'s Democratic Republic', 'LA', 'LAO', '856', 'LAK', 'Kip', '₭', 1],
            [122, 'Latitude', 'LV', 'LVA', '371', 'EUR', 'Euro', '€', 1],
            [123, 'Lebanon', 'LB', 'LBN', '961', 'LBP', 'Lebanese Pound', 'ل.ل', 1],
            [124, 'Lesotho', 'LS', 'LSO', '266', 'LSL', 'Loti', 'L', 1],
            [125, 'Liberia', 'LR', 'LBR', '231', 'LRD', 'Liberian Dollar', '$', 1],
            [126, 'Libya', 'LY', 'LBY', '218', 'LYD', 'Libyan Dinar', 'ل.د', 1],
            [127, 'Liechtenstein', 'LI', 'LIE', '423', 'CHF', 'Swiss Franc', 'CHf', 1],
            [128, 'Lithuania', 'LT', 'LTU', '370', 'EUR', 'Euro', '€', 1],
            [129, 'Luxembourg', 'LU', 'LUX', '352', 'EUR', 'Euro', '€', 1],
            [130, 'Macao', 'MO', 'MAC', '853', 'MOP', 'Pataca', 'MOP$', 1],
            [131, 'Macedonia, the Former Yugoslav Republic of', 'MK', 'MKD', '389', 'MKD', 'Denar', 'ден', 1],
            [132, 'Madagascar', 'MG', 'MDG', '261', 'MGA', 'Malagasy Ariary', 'Ar', 1],
            [133, 'Malawi', 'MW', 'MWI', '265', 'MWK', 'Kwacha', 'MK', 1],
            [134, 'Malaysia', 'MY', 'MYS', '60', 'MYR', 'Malaysian Ringgit', 'RM', 1],
            [135, 'Maldives', 'MV', 'MDV', '960', 'MVR', 'Rufiyaa', 'Rf', 1],
            [136, 'Mali', 'ML', 'MLI', '223', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [137, 'Malta', 'MT', 'MLT', '356', 'EUR', 'Euro', '€', 1],
            [138, 'Marshall Islands', 'MH', 'MHL', '692', 'USD', 'US Dollar', '$', 1],
            [139, 'Martinique', 'MQ', 'MTQ', '596', 'EUR', 'Euro', '€', 1],
            [140, 'Mauritania', 'MR', 'MRT', '222', 'MRU', 'Ouguiya', 'UM', 1],
            [141, 'Mauritius', 'MU', 'MUS', '230', 'MUR', 'Mauritius Rupee', '₨', 1],
            [142, 'Mayotte', 'YT', 'MYT', '262', 'EUR', 'Euro', '€', 1],
            [143, 'Mexico', 'MX', 'MEX', '52', 'MXN', 'Mexican Peso', '$', 1],
            [144, 'Micronesia, Federated States of', 'FM', 'FSM', '691', 'USD', 'US Dollar', '$', 1],
            [145, 'Moldova, Republic of', 'MD', 'MDA', '373', 'MDL', 'Moldovan Leu', 'L', 1],
            [146, 'Monaco', 'MC', 'MCO', '377', 'EUR', 'Euro', '€', 1],
            [147, 'Mongolia', 'MN', 'MNG', '976', 'MNT', 'Tugrik', '₮', 1],
            [148, 'Montenegro', 'ME', 'MNE', '382', 'EUR', 'Euro', '€', 1],
            [149, 'Montserrat', 'MS', 'MSR', '1-664', 'XCD', 'East Caribbean Dollar', '$', 1],
            [150, 'Morocco', 'MA', 'MAR', '212', 'MAD', 'Moroccan Dirham', 'د.م.', 1],
            [151, 'Mozambique', 'MZ', 'MOZ', '258', 'MZN', 'Mozambique Metical', 'MT', 1],
            [152, 'Myanmar', 'MM', 'MMR', '95', 'MMK', 'Kyat', 'K', 1],
            [153, 'Namibia', 'NA', 'NAM', '264', 'NAD', 'Namibia Dollar', '$', 1],
            [154, 'Nauru', 'NR', 'NRU', '674', 'AUD', 'Australian Dollar', '$', 1],
            [155, 'Nepal', 'NP', 'NPL', '977', 'NPR', 'Nepalese Rupee', '₨', 1],
            [156, 'Netherlands', 'NL', 'NLD', '31', 'EUR', 'Euro', '€', 1],
            [157, 'New Caledonia', 'NC', 'NCL', '687', 'XPF', 'CFP Franc', '₣', 1],
            [158, 'New Zealand', 'NZ', 'NZL', '64', 'NZD', 'New Zealand Dollar', '$', 1],
            [159, 'Nicaragua', 'NI', 'NIC', '505', 'NIO', 'Cordoba Oro', 'C$', 1],
            [160, 'Niger', 'NE', 'NER', '227', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [161, 'Nigeria', 'NG', 'NGA', '234', 'NGN', 'Naira', '₦', 1],
            [162, 'Niue', 'NU', 'NIU', '683', 'NZD', 'New Zealand Dollar', '$', 1],
            [163, 'Norfolk Island', 'NF', 'NFK', '672', 'AUD', 'Australian Dollar', '$', 1],
            [164, 'Northern Mariana Islands', 'MP', 'MNP', '1-670', 'USD', 'US Dollar', '$', 1],
            [165, 'Norway', 'NO', 'NOR', '47', 'NOK', 'Norwegian Krone', 'kr', 1],
            [166, 'Oman', 'OM', 'OMN', '968', 'OMR', 'Rial Omani', 'ر.ع.', 1],
            [167, 'Pakistan', 'PK', 'PAK', '92', 'PKR', 'Pakistan Rupee', '₨', 1],
            [168, 'Palau', 'PW', 'PLW', '680', 'USD', 'US Dollar', '$', 1],
            [169, 'Palestine, State of', 'PS', 'PSE', '970', 'ILS', 'Israeli New Shekel', '₪', 1],
            [170, 'Panama', 'PA', 'PAN', '507', 'PAB', 'Balboa', 'B/.', 1],
            [171, 'Papua New Guinea', 'PG', 'PNG', '675', 'PGK', 'Kina', 'K', 1],
            [172, 'Paraguay', 'PY', 'PRY', '595', 'PYG', 'Guarani', '₲', 1],
            [173, 'Peru', 'PE', 'PER', '51', 'PEN', 'Nuevo Sol', 'S/.', 1],
            [174, 'Philippines', 'PH', 'PHL', '63', 'PHP', 'Philippine Peso', '₱', 1],
            [175, 'Pitcairn', 'PN', 'PCN', '870', 'NZD', 'New Zealand Dollar', '$', 1],
            [176, 'Poland', 'PL', 'POL', '48', 'PLN', 'Zloty', 'zł', 1],
            [177, 'Portugal', 'PT', 'PRT', '351', 'EUR', 'Euro', '€', 1],
            [178, 'Puerto Rico', 'PR', 'PRI', '1', 'USD', 'US Dollar', '$', 1],
            [179, 'Qatar', 'QA', 'QAT', '974', 'QAR', 'Qatari Rial', 'ر.ق', 1],
            [180, 'Romania', 'RO', 'ROU', '40', 'RON', 'New Romanian Leu', 'lei', 1],
            [181, 'Russian Federation', 'RU', 'RUS', '7', 'RUB', 'Russian Ruble', '₽', 1],
            [182, 'Rwanda', 'RW', 'RWA', '250', 'RWF', 'Rwanda Franc', 'FRw', 1],
            [183, 'Réunion', 'RE', 'REU', '262', 'EUR', 'Euro', '€', 1],
            [184, 'Saint Barthélemy', 'BL', 'BLM', '590', 'EUR', 'Euro', '€', 1],
            [185, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '290', 'SHP', 'Saint Helena Pound', '£', 1],
            [186, 'Saint Kitts and Nevis', 'KN', 'KNA', '1-869', 'XCD', 'East Caribbean Dollar', '$', 1],
            [187, 'Saint Lucia', 'LC', 'LCA', '1-758', 'XCD', 'East Caribbean Dollar', '$', 1],
            [188, 'Saint Martin (French part)', 'MF', 'MAF', '590', 'EUR', 'Euro', '€', 1],
            [189, 'Saint Pierre and Miquelon', 'PM', 'SPM', '508', 'EUR', 'Euro', '€', 1],
            [190, 'Saint Vincent and the Grenadines', 'VC', 'VCT', '1-784', 'XCD', 'East Caribbean Dollar', '$', 1],
            [191, 'Samoa', 'WS', 'WSM', '685', 'WST', 'Tala', 'T', 1],
            [192, 'San Marino', 'SM', 'SMR', '378', 'EUR', 'Euro', '€', 1],
            [193, 'Sao Tome and Principe', 'ST', 'STP', '239', 'STN', 'Dobra', 'Db', 1],
            [194, 'Saudi Arabia', 'SA', 'SAU', '966', 'SAR', 'Saudi Riyal', 'ر.س', 1],
            [195, 'Senegal', 'SN', 'SEN', '221', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [196, 'Serbia', 'RS', 'SRB', '381', 'RSD', 'Serbian Dinar', 'дин', 1],
            [197, 'Seychelles', 'SC', 'SYC', '248', 'SCR', 'Seychelles Rupee', '₨', 1],
            [198, 'Sierra Leone', 'SL', 'SLE', '232', 'SLL', 'Leone', 'Le', 1],
            [199, 'Singapore', 'SG', 'SGP', '65', 'SGD', 'Singapore Dollar', '$', 1],
            [200, 'Sint Maarten (Dutch part)', 'SX', 'SXM', '1-721', 'ANG', 'Netherlands Antillean Guilder', 'ƒ', 1],
            [201, 'Slovakia', 'SK', 'SVK', '421', 'EUR', 'Euro', '€', 1],
            [202, 'Slovenia', 'SI', 'SVN', '386', 'EUR', 'Euro', '€', 1],
            [203, 'Solomon Islands', 'SB', 'SLB', '677', 'SBD', 'Solomon Islands Dollar', '$', 1],
            [204, 'Somalia', 'SO', 'SOM', '252', 'SOS', 'Somali Shilling', 'Sh', 1],
            [205, 'South Africa', 'ZA', 'ZAF', '27', 'ZAR', 'Rand', 'R', 1],
            [206, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '500', 'GBP', 'Pound Sterling', '£', 1],
            [207, 'South Sudan', 'SS', 'SSD', '211', 'SSP', 'South Sudanese Pound', '£', 1],
            [208, 'Spain', 'ES', 'ESP', '34', 'EUR', 'Euro', '€', 1],
            [209, 'Sri Lanka', 'LK', 'LKA', '94', 'LKR', 'Sri Lanka Rupee', '₨', 1],
            [210, 'Sudan', 'SD', 'SDN', '249', 'SDG', 'Sudanese Pound', '£', 1],
            [211, 'Suriname', 'SR', 'SUR', '597', 'SRD', 'Surinam Dollar', '$', 1],
            [212, 'Svalbard and Jan Mayen', 'SJ', 'SJM', '47', 'NOK', 'Norwegian Krone', 'kr', 1],
            [213, 'Swaziland', 'SZ', 'SWZ', '268', 'SZL', 'Lilangeni', 'L', 1],
            [214, 'Sweden', 'SE', 'SWE', '46', 'SEK', 'Swedish Krona', 'kr', 1],
            [215, 'Switzerland', 'CH', 'CHE', '41', 'CHF', 'Swiss Franc', 'CHf', 1],
            [216, 'Syrian Arab Republic', 'SY', 'SYR', '963', 'SYP', 'Syrian Pound', '£', 1],
            [217, 'Taiwan, Province of China', 'TW', 'TWN', '886', 'TWD', 'New Taiwan Dollar', '$', 1],
            [218, 'Tajikistan', 'TJ', 'TJK', '992', 'TJS', 'Somoni', 'SM', 1],
            [219, 'Tanzania, United Republic of', 'TZ', 'TZA', '255', 'TZS', 'Tanzanian Shilling', 'TSh', 1],
            [220, 'Thailand', 'TH', 'THA', '66', 'THB', 'Baht', '฿', 1],
            [221, 'Timor-Leste', 'TL', 'TLS', '670', 'USD', 'US Dollar', '$', 1],
            [222, 'Togo', 'TG', 'TGO', '228', 'XOF', 'CFA Franc BCEAO', 'CFA', 1],
            [223, 'Tokelau', 'TK', 'TKL', '690', 'NZD', 'New Zealand Dollar', '$', 1],
            [224, 'Tonga', 'TO', 'TON', '676', 'TOP', 'Pa\'anga', 'T$', 1],
            [225, 'Trinidad and Tobago', 'TT', 'TTO', '1-868', 'TTD', 'Trinidad and Tobago Dollar', '$', 1],
            [226, 'Tunisia', 'TN', 'TUN', '216', 'TND', 'Tunisian Dinar', 'د.ت', 1],
            [227, 'Turkey', 'TR', 'TUR', '90', 'TRY', 'Turkish Lira', '₺', 1],
            [228, 'Turkmenistan', 'TM', 'TKM', '993', 'TMT', 'Turkmenistan New Manat', 'm', 1],
            [229, 'Turks and Caicos Islands', 'TC', 'TCA', '1-649', 'USD', 'US Dollar', '$', 1],
            [230, 'Tuvalu', 'TV', 'TUV', '688', 'AUD', 'Australian Dollar', '$', 1],
            [231, 'Uganda', 'UG', 'UGA', '256', 'UGX', 'Uganda Shilling', 'USh', 1],
            [232, 'Ukraine', 'UA', 'UKR', '380', 'UAH', 'Hryvnia', '₴', 1],
            [233, 'United Arab Emirates', 'AE', 'ARE', '971', 'AED', 'UAE Dirham', 'د.إ', 1],
            [234, 'United Kingdom', 'GB', 'GBR', '44', 'GBP', 'Pound Sterling', '£', 1],
            [235, 'United States', 'US', 'USA', '1', 'USD', 'US Dollar', '$', 1],
            [236, 'United States Minor Outlying Islands', 'UM', 'UMI', '1', 'USD', 'US Dollar', '$', 1],
            [237, 'Uruguay', 'UY', 'URY', '598', 'UYU', 'Peso Uruguayo', '$', 1],
            [238, 'Uzbekistan', 'UZ', 'UZB', '998', 'UZS', 'Uzbekistan Sum', 'лв', 1],
            [239, 'Vanuatu', 'V极', 'VUT', '678', 'VUV', 'Vatu', 'VT', 1],
            [240, 'Venezuela, Bolivarian Republic of', 'VE', 'VEN', '58', 'VES', 'Bolívar Soberano', 'Bs.S', 1],
            [241, 'Viet Nam', 'VN', 'VNM', '84', 'VND', 'Dong', '₫', 1],
            [242, 'Virgin Islands, British', 'VG', '极GB', '1-284', 'USD', 'US Dollar', '$', 1],
            [243, 'Virgin Islands, U.S.', 'VI', 'VIR', '1-340', 'USD', 'US Dollar', '$', 1],
            [244, 'Wallis and Futuna', 'WF', 'WLF', '681', 'XPF', 'CFP Franc', '₣', 1],
            [245, 'Western Sahara', 'EH', 'ESH', '212', 'MAD', 'Moroccan Dirham', 'د.م.', 1],
            [246, 'Yemen', 'YE', 'YEM', '极67', 'YER', 'Yemeni Rial', '﷼', 1],
            [247, 'Zambia', 'ZM', 'ZMB', '260', 'ZMW', 'Zambian Kwacha', 'ZK', 1],
            [248, 'Zimbabwe', 'ZW', 'ZWE', '263', 'ZWL', 'Zimbabwe Dollar', '$', 1],
            [249, 'Åland Islands', 'AX', 'ALA', '358', 'EUR', 'Euro', '€', 1],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'id' => $country[0],
                'name' => $country[1],
                'iso' => $country[2],
                'iso3' => $country[3],
                'dial' => $country[4],
                'currency' => $country[5],
                'currency_name' => $country[6],
                'currency_symbol' => $country[7],
                'status' => $country[8],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
