@extends('catalog.layout')
@section('content')
<div class="catalog-shell">
    <section class="catalog-hero"><div class="catalog-hero__content"><x-catalog.badge tone="accent">Multi-provider catalog</x-catalog.badge><h1>{{ auth()->check() ? 'Your personalized game discovery starts here.' : 'Find your next game without digging through four different sites.' }}</h1><p>Explore popular releases, free-to-play games, active giveaways and current deals from one clean catalog.</p><form action="{{ route('catalog.search') }}" method="GET" class="catalog-search catalog-search--hero" role="search" data-search-form><label class="sr-only" for="hero-game-search">Search the game catalog</label><input id="hero-game-search" name="q" type="search" placeholder="Search by game title..." maxlength="120"><button type="submit">Search games</button></form></div></section>

    @auth
        <section class="catalog-section"><x-catalog.section-header title="For You" subtitle="Ranked from your preferred genres and platforms, with sensible defaults when preferences are empty." :href="route('catalog.user.settings')" />
            @if($personalized)<div class="game-grid">@foreach($personalized as $game)<x-catalog.game-card :game="$game" />@endforeach</div>@else<x-catalog.state title="Personalization will improve as you browse" message="Choose genres/platforms or view a few games to get started." />@endif
        </section>
        @if($recent)<section class="catalog-section"><x-catalog.section-header title="Recently Viewed" subtitle="Your latest catalog visits, newest first." :href="route('catalog.user.library')" /><div class="game-grid game-grid--compact">@foreach($recent as $game)<x-catalog.game-card :game="$game" />@endforeach</div></section>@endif
        @if($saved)<section class="catalog-section"><x-catalog.section-header title="Saved Games" subtitle="Your cross-provider watchlist." :href="route('catalog.user.library')" /><div class="game-grid game-grid--compact">@foreach($saved as $game)<x-catalog.game-card :game="$game" />@endforeach</div></section>@endif
    @endauth

    <section class="catalog-section"><x-catalog.section-header title="Trending & discover" subtitle="Highly rated picks from the RAWG catalog." />@if($discover)<div class="game-grid">@foreach($discover as $game)<x-catalog.game-card :game="$game" />@endforeach</div>@else<x-catalog.state title="Discover games are temporarily unavailable" message="The provider may be unavailable; other sections continue independently." type="error" />@endif</section>
    @if($genres || $platforms)<section class="catalog-filter-panel"><div><h2>Browse by genre or platform</h2><p>Use these filters or save them as preferences from Gaming Settings.</p></div>@if($genres)<div class="catalog-chip-group"><strong>Genres</strong><div>@foreach($genres as $genre)<a class="catalog-chip" href="{{ route('catalog.index', ['genre' => $genre['slug'] ?? $genre['id']]) }}">{{ $genre['name'] }}</a>@endforeach</div></div>@endif @if($platforms)<div class="catalog-chip-group"><strong>Platforms</strong><div>@foreach($platforms as $platform)<a class="catalog-chip" href="{{ route('catalog.index', ['platform' => $platform['slug'] ?? $platform['id']]) }}">{{ $platform['name'] }}</a>@endforeach</div></div>@endif</section>@endif
    <section class="catalog-section"><x-catalog.section-header title="Free-to-play" subtitle="Games you can start without an upfront purchase." :href="route('catalog.free')" />@if($free)<div class="game-grid game-grid--compact">@foreach($free as $game)<x-catalog.game-card :game="$game" />@endforeach</div>@else<x-catalog.state title="No free-to-play games available right now" message="Try again later." />@endif</section>
    <section class="catalog-section"><x-catalog.section-header title="Active giveaways" subtitle="Limited-time offers sourced from GamerPower." :href="route('catalog.giveaways')" />@if($giveaways)<div class="giveaway-grid">@foreach($giveaways as $game)<x-catalog.giveaway-card :game="$game" />@endforeach</div>@else<x-catalog.state title="No giveaways available right now" message="This section fails safely when the provider is unavailable." />@endif</section>
    <section class="catalog-section"><x-catalog.section-header title="Game deals" subtitle="Recent discounts from CheapShark." :href="route('catalog.deals')" />@if($deals)<div class="deal-list">@foreach($deals as $game)<x-catalog.price-deal-card :game="$game" />@endforeach</div>@else<x-catalog.state title="Deals are temporarily unavailable" message="Other sections remain available." />@endif</section>
</div>
@endsection
